/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v3/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Root */
        get: operations["read_root_v3__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/year/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single year
         * @description Returns a single Year object. Requires a four-digit year, e.g. `2019`.
         */
        get: operations["read_year_v3_year__year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Query multiple years */
        get: operations["read_years_v3_years_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/team/{team}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single team
         * @description Returns a single Team object. Requires a team number (no prefix).
         */
        get: operations["read_team_v3_team__team__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple teams
         * @description Returns up to 1000 teams at a time. Specify limit and offset to page through results.
         */
        get: operations["read_teams_v3_teams_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/team_year/{team}/{year}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single team year
         * @description Returns a single Team Year object. Requires a team number and year.
         */
        get: operations["read_team_year_v3_team_year__team___year__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/team_years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple team years
         * @description Returns up to 1000 team years at a time. Specify limit and offset to page through results.
         */
        get: operations["read_team_years_v3_team_years_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/event/{event}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single event
         * @description Returns a single Event object. Requires an event key, e.g. `2019ncwak`.
         */
        get: operations["read_event_v3_event__event__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple events
         * @description Returns up to 1000 events at a time. Specify limit and offset to page through results.
         */
        get: operations["read_events_v3_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/team_event/{team}/{event}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single team event
         * @description Returns a single Team Event object. Requires a team number and event key, e.g. `5511` and `2019ncwak`.
         */
        get: operations["read_team_event_v3_team_event__team___event__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/team_events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple team events
         * @description Returns up to 1000 team events at a time. Specify limit and offset to page through results.
         */
        get: operations["read_team_events_v3_team_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/match/{match}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query a single match
         * @description Returns a single Match object. Requires a match key, e.g. `2019ncwak_f1m1`.
         */
        get: operations["read_match_v3_match__match__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v3/matches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query multiple matches
         * @description Returns up to 1000 matches at a time. Specify limit and offset to page through results.
         */
        get: operations["read_matches_v3_matches_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_root_v3__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    read_year_v3_year__year__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_years_v3_years_get: {
        parameters: {
            query?: {
                /** @description How to sort the returned values. Any column in the table is valid. */
                metric?: string | null;
                /** @description Whether to sort the returned values in ascending order. Default is ascending */
                ascending?: boolean | null;
                /** @description Maximum number of events to return. Default is 1000. */
                limit?: number | null;
                /** @description Offset from the first result to return. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Returns a list of Years since 2002. Older data is not available. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_team_v3_team__team__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_teams_v3_teams_get: {
        parameters: {
            query?: {
                /** @description Capitalized country name, e.g. `USA` or `Canada`. */
                country?: string | null;
                /** @description Capitalized two-letter state code, e.g. `NC`. */
                state?: string | null;
                /** @description One of [`ca`, `fch`, `fim`, `fin`, `fit`, `fma`, `fnc`, `fsc`, `isr`, `ne`, `ont`, `pch`, `pnw`, `win`] */
                district?: string | null;
                /** @description Whether the team has played in the last year. */
                active?: boolean | null;
                /** @description How to sort the returned values. Any column in the table is valid. */
                metric?: string;
                /** @description Whether to sort the returned values in ascending order. Default is ascending */
                ascending?: boolean;
                /** @description Maximum number of events to return. Default is 1000. */
                limit?: number;
                /** @description Offset from the first result to return. */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_team_year_v3_team_year__team___year__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
                year: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_team_years_v3_team_years_get: {
        parameters: {
            query?: {
                /** @description Team number (no prefix), e.g. 5511. */
                team?: number | null;
                /** @description Four-digit year */
                year?: number | null;
                /** @description Capitalized country name, e.g. `USA` or `Canada`. */
                country?: string | null;
                /** @description Capitalized two-letter state code, e.g. `NC`. */
                state?: string | null;
                /** @description One of [`ca`, `fch`, `fim`, `fin`, `fit`, `fma`, `fnc`, `fsc`, `isr`, `ne`, `ont`, `pch`, `pnw`, `win`] */
                district?: string | null;
                /** @description How to sort the returned values. Any column in the table is valid. */
                metric?: string | null;
                /** @description Whether to sort the returned values in ascending order. Default is ascending */
                ascending?: boolean | null;
                /** @description Maximum number of events to return. Default is 1000. */
                limit?: number | null;
                /** @description Offset from the first result to return. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_event_v3_event__event__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_events_v3_events_get: {
        parameters: {
            query?: {
                /** @description Four-digit year */
                year?: number | null;
                /** @description Capitalized country name, e.g. `USA` or `Canada`. */
                country?: string | null;
                /** @description Capitalized two-letter state code, e.g. `NC`. */
                state?: string | null;
                /** @description One of [`ca`, `fch`, `fim`, `fin`, `fit`, `fma`, `fnc`, `fsc`, `isr`, `ne`, `ont`, `pch`, `pnw`, `win`] */
                district?: string | null;
                /** @description One of [`regional`, `district`, `district_cmp`, `champs_div`, `einstein`, or `offseason`]. */
                type?: string | null;
                /** @description Week of the competition season. 8 is CMP */
                week?: number | null;
                /** @description How to sort the returned values. Any column in the table is valid. */
                metric?: string | null;
                /** @description Whether to sort the returned values in ascending order. Default is ascending */
                ascending?: boolean | null;
                /** @description Maximum number of events to return. Default is 1000. */
                limit?: number | null;
                /** @description Offset from the first result to return. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_team_event_v3_team_event__team___event__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team: number;
                event: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_team_events_v3_team_events_get: {
        parameters: {
            query?: {
                /** @description Team number (no prefix), e.g. 5511. */
                team?: number | null;
                /** @description Four-digit year */
                year?: number | null;
                /** @description Event key, e.g. `2019ncwak`. */
                event?: string | null;
                /** @description Capitalized country name, e.g. `USA` or `Canada`. */
                country?: string | null;
                /** @description Capitalized two-letter state code, e.g. `NC`. */
                state?: string | null;
                /** @description One of [`ca`, `fch`, `fim`, `fin`, `fit`, `fma`, `fnc`, `fsc`, `isr`, `ne`, `ont`, `pch`, `pnw`, `win`] */
                district?: string | null;
                /** @description One of [`regional`, `district`, `district_cmp`, `champs_div`, `einstein`, or `offseason`]. */
                type?: string | null;
                /** @description Week of the competition season. 8 is CMP */
                week?: number | null;
                /** @description How to sort the returned values. Any column in the table is valid. */
                metric?: string | null;
                /** @description Whether to sort the returned values in ascending order. Default is ascending */
                ascending?: boolean | null;
                /** @description Maximum number of events to return. Default is 1000. */
                limit?: number | null;
                /** @description Offset from the first result to return. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_match_v3_match__match__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                match: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_matches_v3_matches_get: {
        parameters: {
            query?: {
                /** @description Team number (no prefix), e.g. 5511. */
                team?: number | null;
                /** @description Four-digit year */
                year?: number | null;
                /** @description Event key, e.g. `2019ncwak`. */
                event?: string | null;
                /** @description Week of the competition season. 8 is CMP */
                week?: number | null;
                /** @description Whether the match is an elimination match. */
                elim?: boolean | null;
                /** @description How to sort the returned values. Any column in the table is valid. */
                metric?: string | null;
                /** @description Whether to sort the returned values in ascending order. Default is ascending */
                ascending?: boolean | null;
                /** @description Maximum number of events to return. Default is 1000. */
                limit?: number | null;
                /** @description Offset from the first result to return. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
